<template>
  <div class="staff-payments">
    <h1>Payment Processing</h1>
    <p class="subtitle">Generate payment batches for approved scholarship applications</p>

    <!-- Tabs -->
    <div class="tabs">
      <button :class="{ active: activeTab === 'eligible' }" @click="activeTab = 'eligible'; loadEligible()">
        Eligible for Payment
      </button>
      <button :class="{ active: activeTab === 'batches' }" @click="activeTab = 'batches'; loadBatches()">
        Payment Batches
      </button>
      <button :class="{ active: activeTab === 'duplicates' }" @click="activeTab = 'duplicates'; loadDuplicates()">
        Duplicate Detection
      </button>
    </div>

    <!-- Messages -->
    <goa-callout v-if="error" type="emergency" heading="Error">{{ error }}</goa-callout>
    <goa-callout v-if="success" type="success" heading="Success">{{ success }}</goa-callout>

    <!-- Loading -->
    <div v-if="loading" class="loading">
      <goa-circular-progress size="large"></goa-circular-progress>
    </div>

    <!-- Eligible Applications Tab -->
    <div v-if="!loading && activeTab === 'eligible'">
      <div class="action-bar">
        <span>{{ selectedIds.length }} of {{ eligibleApps.length }} selected</span>
        <goa-button type="primary" @_click="generateBatch" :disabled="selectedIds.length === 0 || generating">
          {{ generating ? 'Generating...' : 'Generate Payment Batch' }}
        </goa-button>
      </div>

      <div v-if="eligibleApps.length === 0" class="empty-state">
        <p>No approved applications with direct deposit setup.</p>
      </div>
      <table v-else class="data-table">
        <thead>
          <tr>
            <th><input type="checkbox" @change="toggleAll" :checked="selectedIds.length === eligibleApps.filter(a => a.has_banking).length" /></th>
            <th>Reference #</th>
            <th>Applicant</th>
            <th>Scholarship</th>
            <th>Amount</th>
            <th>Bank Info</th>
            <th>Account</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="app in eligibleApps" :key="app.id" :class="{ 'no-banking': !app.has_banking }">
            <td>
              <input type="checkbox" :disabled="!app.has_banking" :checked="selectedIds.includes(app.id)"
                @change="toggleSelect(app.id)" />
            </td>
            <td>{{ app.reference_number }}</td>
            <td>{{ app.display_name }}</td>
            <td>{{ app.scholarship_name }}</td>
            <td class="amount">${{ app.amount.toFixed(2) }}</td>
            <td>
              <span v-if="app.has_banking" class="badge badge-ok">DD Setup</span>
              <span v-else class="badge badge-warn">No DD</span>
            </td>
            <td>{{ app.has_banking ? `${app.institution_number}-${app.transit_number} ${app.account_masked}` : '-' }}</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="4" class="total-label">Selected Total:</td>
            <td class="amount total-amount">${{ selectedTotal.toFixed(2) }}</td>
            <td colspan="2"></td>
          </tr>
        </tfoot>
      </table>
    </div>

    <!-- Batches Tab -->
    <div v-if="!loading && activeTab === 'batches'">
      <div v-if="batches.length === 0" class="empty-state">
        <p>No payment batches generated yet.</p>
      </div>
      <table v-else class="data-table">
        <thead>
          <tr>
            <th>Batch #</th>
            <th>Generated By</th>
            <th>Applications</th>
            <th>Total Amount</th>
            <th>Status</th>
            <th>Date</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="batch in batches" :key="batch.id">
            <td>{{ batch.batch_number }}</td>
            <td>{{ batch.generated_by_name }}</td>
            <td>{{ batch.application_count }}</td>
            <td class="amount">${{ parseFloat(batch.total_amount).toFixed(2) }}</td>
            <td>
              <span class="badge" :class="batch.status === 'Paid' ? 'badge-ok' : 'badge-pending'">
                {{ batch.status }}
              </span>
            </td>
            <td>{{ formatDate(batch.created_at) }}</td>
            <td>
              <goa-button v-if="batch.status === 'Generated'" type="tertiary" size="compact" @_click="confirmPayment(batch.id)">
                Confirm Paid
              </goa-button>
              <goa-button type="tertiary" size="compact" @_click="downloadBatch(batch)">
                Download
              </goa-button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Duplicates Tab -->
    <div v-if="!loading && activeTab === 'duplicates'">
      <div v-if="duplicates.length === 0" class="empty-state">
        <goa-callout type="success" heading="No Duplicates">
          No duplicate bank accounts detected.
        </goa-callout>
      </div>
      <table v-else class="data-table">
        <thead>
          <tr>
            <th>User 1</th>
            <th>User 2</th>
            <th>Institution #</th>
            <th>Transit #</th>
            <th>Account</th>
            <th>Flagged</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(dup, idx) in duplicates" :key="idx" class="duplicate-row">
            <td>{{ dup.user1_name }}<br /><small>{{ dup.user1_email }}</small></td>
            <td>{{ dup.user2_name }}<br /><small>{{ dup.user2_email }}</small></td>
            <td>{{ dup.institution_number }}</td>
            <td>{{ dup.transit_number }}</td>
            <td>{{ dup.account_masked }}</td>
            <td>{{ formatDate(dup.user2_created) }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { paymentAPI } from '@/services/paymentService';

const activeTab = ref('eligible');
const loading = ref(true);
const error = ref(null);
const success = ref(null);
const generating = ref(false);

const eligibleApps = ref([]);
const selectedIds = ref([]);
const batches = ref([]);
const duplicates = ref([]);

const selectedTotal = computed(() => {
  return eligibleApps.value
    .filter(a => selectedIds.value.includes(a.id))
    .reduce((sum, a) => sum + a.amount, 0);
});

onMounted(() => loadEligible());

async function loadEligible() {
  loading.value = true;
  error.value = null;
  try {
    eligibleApps.value = await paymentAPI.getEligible();
    selectedIds.value = [];
  } catch (err) {
    error.value = err.response?.data?.message || err.message || 'Failed to load eligible applications';
  } finally {
    loading.value = false;
  }
}

async function loadBatches() {
  loading.value = true;
  error.value = null;
  try {
    const res = await paymentAPI.getBatches();
    batches.value = res.data || [];
  } catch (err) {
    error.value = err.response?.data?.message || err.message || 'Failed to load batches';
  } finally {
    loading.value = false;
  }
}

async function loadDuplicates() {
  loading.value = true;
  error.value = null;
  try {
    duplicates.value = await paymentAPI.getDuplicates();
  } catch (err) {
    error.value = err.response?.data?.message || err.message || 'Failed to check duplicates';
  } finally {
    loading.value = false;
  }
}

function toggleAll(e) {
  if (e.target.checked) {
    selectedIds.value = eligibleApps.value.filter(a => a.has_banking).map(a => a.id);
  } else {
    selectedIds.value = [];
  }
}

function toggleSelect(id) {
  const idx = selectedIds.value.indexOf(id);
  if (idx >= 0) selectedIds.value.splice(idx, 1);
  else selectedIds.value.push(id);
}

async function generateBatch() {
  if (selectedIds.value.length === 0) return;
  generating.value = true;
  error.value = null;
  success.value = null;
  try {
    const result = await paymentAPI.generateBatch(selectedIds.value);
    success.value = `Payment batch ${result.batch_number} generated: ${result.application_count} applications, $${result.total_amount.toFixed(2)} total`;

    // Trigger download of 1GX file
    if (result.file_content) {
      const blob = new Blob([result.file_content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = result.file_name;
      a.click();
      URL.revokeObjectURL(url);
    }

    // Refresh eligible list
    await loadEligible();
  } catch (err) {
    error.value = err.response?.data?.message || err.message || 'Failed to generate batch';
  } finally {
    generating.value = false;
  }
}

async function confirmPayment(batchId) {
  error.value = null;
  try {
    const result = await paymentAPI.confirmBatch(batchId);
    success.value = `Batch confirmed as paid: ${result.count} applications`;
    setTimeout(() => success.value = null, 5000);
    loadBatches();
  } catch (err) {
    error.value = err.response?.data?.message || err.message || 'Failed to confirm payment';
  }
}

function downloadBatch(batch) {
  // Re-download would need the file content - for now show info
  success.value = `Batch file: ${batch.file_name}`;
  setTimeout(() => success.value = null, 3000);
}

function formatDate(d) {
  if (!d) return '-';
  return new Date(d).toLocaleDateString('en-CA', { year: 'numeric', month: 'short', day: 'numeric' });
}
</script>

<style scoped>
.staff-payments { max-width: 1200px; margin: 0 auto; padding: 24px; }
.subtitle { color: #666; margin-bottom: 24px; }

.tabs { display: flex; gap: 0; margin-bottom: 24px; border-bottom: 2px solid #ddd; }
.tabs button {
  padding: 10px 20px; border: none; background: none; cursor: pointer;
  font-size: 14px; color: #666; border-bottom: 2px solid transparent; margin-bottom: -2px;
}
.tabs button.active { color: #0070c4; border-bottom-color: #0070c4; font-weight: 600; }

.action-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px; padding: 12px 16px; background: #f1f1f1; border-radius: 6px; }

.data-table { width: 100%; border-collapse: collapse; }
.data-table th { background: #f1f1f1; padding: 10px 12px; text-align: left; font-size: 13px; font-weight: 600; border-bottom: 2px solid #ddd; }
.data-table td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 14px; }
.data-table tr:hover { background: #f8f9fa; }
.data-table tr.no-banking { background: #fff8e1; }
.data-table tr.duplicate-row { background: #ffeef0; }
.data-table tfoot td { font-weight: 600; border-top: 2px solid #ddd; }

.amount { text-align: right; font-family: monospace; }
.total-label { text-align: right; }
.total-amount { font-size: 16px; color: #0070c4; }

.badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; }
.badge-ok { background: #d4edda; color: #155724; }
.badge-warn { background: #fff3cd; color: #856404; }
.badge-pending { background: #cce5ff; color: #004085; }

.empty-state { text-align: center; padding: 40px; color: #666; }
.loading { text-align: center; padding: 60px; }
small { color: #666; }
</style>
